on:
  pull_request:
    branches:
      - main
    paths:
      - 'Localizable.xcstrings'

jobs:
  update_localizations:
    name: Update Localization strings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff FETCH_HEAD...${{ github.sha }} -- Localizable.xcstrings | python .github/scripts/update_localizations.py
